### ISSUE TITLE
Error building chameleon with current rust 

### ISSUE THREAD

**Issue by echelon2020** [cameleon-rs/cameleon#124]
- What did you expect to happen? What did actually happen?

building cameleon-rs on Mac OS using stable rust 

stable-x86_64-apple-darwin (default)
rustc 1.58.0 (02072b482 2022-01-11)

Compiling cameleon v0.1.3 (/Users/uwehagmaier/Documents/work/rust/cameleon/cameleon)
error: unused attribute
   --> cameleon/src/u3v/control_handle.rs:514:15
    |
514 |               $(#[$meta])*
    |                 ^^^^^^^^ help: remove this attribute
...
540 | /     impl_shared_control_handle!(
541 | |         /// Thread safe version of [`ControlHandle::buffer_capacity`].
542 | |         #[must_use]
543 | |         pub fn buffer_capacity(&self) -> usize,
...   |
556 | |         pub fn set_retry_count(&self, count: u16) -> ()
557 | |     );
    | |_____- in this macro invocation
    |
    = note: `-D unused-attributes` implied by `-D warnings`
note: attribute also specified here
   --> cameleon/src/u3v/control_handle.rs:514:15
    |
514 |               $(#[$meta])*
    |                 ^^^^^^^^
...
540 | /     impl_shared_control_handle!(
541 | |         /// Thread safe version of [`ControlHandle::buffer_capacity`].
542 | |         #[must_use]
543 | |         pub fn buffer_capacity(&self) -> usize,
...   |
556 | |         pub fn set_retry_count(&self, count: u16) -> ()
557 | |     );
    | |_____- in this macro invocation
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: this error originates in the macro `impl_shared_control_handle` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `cameleon` due to previous error

- How to reproduce the issue?
git clone ....
cd cameleon
cargo build

### Meta
- Which manufacturer's camera did you use?
- What is the model name of the camera?

- Which `Cameleon` version are you using?
- 0.1.0

**Comment by echelon2020** [comment]
Seems to build with rust 1.56.0  .....

**Comment by Y-Nak** [comment]
@echelon2020 Thanks for opening an issue! I fixed this in #125, also I'll bump up the version to `0.1.4`.
Please feel free to reopen the issue if the problem is not fixed yet.

**Comment by echelon2020** [comment]
Thank you. Builds now!
