### ISSUE TITLE
Build of test app fails with error in cargo.toml

### ISSUE THREAD

**Issue by echelon2020** [cameleon-rs/cameleon#127]
Using this cargo.toml

[package]
name = "hello_u3v"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cameleon = { version = 0.1, features = 'libusb'}

****************
building fails with:

hello_u3v % cargo build
error: failed to parse manifest at `/Users/......../Documents/work/rust/hello_u3v/Cargo.toml`

Caused by:
  invalid type: string "libusb", expected a sequence for key `dependencies.cameleon.features`

**Comment by Y-Nak** [comment]
Oh, sorry I typo that line in README.
`cameleon = { version = "0.1", features = ["libusb"] }` would work.
I'll fix README later, thanks for notification!

**Comment by echelon2020** [comment]
Hi

Thank you very much. That works now.
I am still at very very beginning in rust. Otherwise I would have been able to find out myself….

Regards
Uwe

> Am 26.01.2022 um 11:30 schrieb Yoshitomo Nakanishi ***@***.***>:
> 
> cameleon = { version = "0.1", features = ["libusb"] }

**Comment by Y-Nak** [comment]
Thanks for your contribution!
