### ISSUE TITLE
Panic when loading camera context

### ISSUE THREAD

**Issue by H2WO4** [cameleon-rs/cameleon#138]
- What did you expect to happen? What did actually happen?

Whenever `camera.load_context()` is called, the programs panic
If there actually was an error, an `Err` should be returned

- How to reproduce the issue?

Trying to load the camera's context
But as the error appears to relate to the XML parser, it could be specific to the camera's settings

### Meta
- Which manufacturer's camera did you use?

Baumer

- What is the model name of the camera?

VCXU-53C

- Which `Cameleon` version are you using?

`0.1.5`

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'main' panicked at 'internal error: entered unreachable code', /home/arthur/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.5/src/parser/elem_type.rs:522:18
stack backtrace:
   0:     0x55e4d9e4cc00 - std::backtrace_rs::backtrace::libunwind::trace::hde47b68928dcaf14
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x55e4d9e4cc00 - std::backtrace_rs::backtrace::trace_unsynchronized::h0e9f7e6d981b3e85
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e4d9e4cc00 - std::sys_common::backtrace::_print_fmt::h4fb0b8ffaca1ed8c
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55e4d9e4cc00 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3a0a95877f1aaacf
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55e4d9e73d4c - core::fmt::write::ha6948f64207814ce
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/fmt/mod.rs:1198:17
   5:     0x55e4d9e47e65 - std::io::Write::write_fmt::h33c62eedfd583516
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/io/mod.rs:1672:15
   6:     0x55e4d9e4e481 - std::sys_common::backtrace::_print::hac94c2c4d30c3dfa
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55e4d9e4e481 - std::sys_common::backtrace::print::h1d4a8d00c15466ff
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55e4d9e4e481 - std::panicking::default_hook::{{closure}}::h9781381e0a05a0b4
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:295:22
   9:     0x55e4d9e4e153 - std::panicking::default_hook::h280a97f20087fbb9
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:314:9
  10:     0x55e4d9e4eb23 - std::panicking::rust_panic_with_hook::he5abf4bf448460c4
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:698:17
  11:     0x55e4d9e4e9d9 - std::panicking::begin_panic_handler::{{closure}}::h0a4b4072565946b1
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:586:13
  12:     0x55e4d9e4d124 - std::sys_common::backtrace::__rust_end_short_backtrace::h388d87ea23aa6430
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55e4d9e4e742 - rust_begin_unwind
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
  14:     0x55e4d9b41613 - core::panicking::panic_fmt::h61ac70f5befc8a11
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
  15:     0x55e4d9b414dd - core::panicking::panic::hd034c7be118323f6
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:48:5
  16:     0x55e4d9ba18cf - cameleon_genapi::parser::elem_type::<impl cameleon_genapi::parser::Parse for cameleon_genapi::elem_type::ValueKind<T>>::parse::h0099a7d65ae6a6cf
  17:     0x55e4d9ba8e15 - cameleon_genapi::parser::integer::<impl cameleon_genapi::parser::Parse for cameleon_genapi::integer::IntegerNode>::parse::h4c5fc1613591dd76
  18:     0x55e4d9b98ffb - <alloc::vec::Vec<cameleon_genapi::store::NodeData> as cameleon_genapi::parser::Parse>::parse::he70e196699283e52
  19:     0x55e4d9b83f99 - cameleon_genapi::parser::xml::Node::parse::h9582adeaa6131c3f
  20:     0x55e4d9b98a0f - <alloc::vec::Vec<cameleon_genapi::store::NodeData> as cameleon_genapi::parser::Parse>::parse::he70e196699283e52
  21:     0x55e4d9b99dad - cameleon_genapi::parser::parse::h5f679bedfd449074
  22:     0x55e4d9b857ef - cameleon_genapi::builder::GenApiBuilder<T,U,S>::build::h6a3b2b57d9f20826
  23:     0x55e4d9ba7607 - <cameleon::genapi::DefaultGenApiCtxt as cameleon::genapi::FromXml>::from_xml::hd772ee16dba53d28
  24:     0x55e4d9b91883 - cameleon::camera::Camera<Ctrl,Strm,Ctxt>::load_context::h89969b702697631d
  25:     0x55e4d9b82580 - rustpsycle::init_cameras::hd80ce1c711a85614
  26:     0x55e4d9b44361 - bench::main::he232454079cdd9fd
  27:     0x55e4d9b6b8b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2c8cf71f2b85832c
  28:     0x55e4d9b7e0f9 - std::rt::lang_start::{{closure}}::hc88a105ac3c060d4
  29:     0x55e4d9e420ca - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h19b0cede2f5c2690
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/ops/function.rs:280:13
  30:     0x55e4d9e420ca - std::panicking::try::do_call::h6c713fba0b0d843f
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  31:     0x55e4d9e420ca - std::panicking::try::h2848a19845bef32f
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  32:     0x55e4d9e420ca - std::panic::catch_unwind::h4c2a1367a86f971f
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  33:     0x55e4d9e420ca - std::rt::lang_start_internal::{{closure}}::hb5a962b3c1a68918
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/rt.rs:128:48
  34:     0x55e4d9e420ca - std::panicking::try::do_call::hd4e5d408cec9b553
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  35:     0x55e4d9e420ca - std::panicking::try::h65647b1c309d0a8b
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  36:     0x55e4d9e420ca - std::panic::catch_unwind::ha9c9d1d412410665
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  37:     0x55e4d9e420ca - std::rt::lang_start_internal::h50ce8cee9cd80dd8
                               at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/rt.rs:128:20
  38:     0x55e4d9b45c02 - main
  39:     0x7fc778801d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  40:     0x7fc778801e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  41:     0x55e4d9b41965 - _start
  42:                0x0 - <unknown>
```

</p>
</details>

**Comment by H2WO4** [comment]
I've looked a bit into the source of the error

It seems like cameleon do not handles `"pInvalidator"` when it is inside `Integer`

Here is the code (in `src/parser/elem_type.rs`):

```rs
impl<T> Parse for ValueKind<T>
where
    T: Clone + Parse + PartialEq,
    ImmOrPNode<T>: Parse,
{
    fn parse(
        node: &mut xml::Node,
        node_builder: &mut impl NodeStoreBuilder,
        value_builder: &mut impl ValueStoreBuilder,
        cache_builder: &mut impl CacheStoreBuilder,
    ) -> Self {
        let peek = node.peek().unwrap();
        match peek.tag_name() {
            VALUE => ValueKind::Value(node.parse(node_builder, value_builder, cache_builder)),
            P_VALUE_COPY | P_VALUE => {
                let p_value = node.parse(node_builder, value_builder, cache_builder);
                ValueKind::PValue(p_value)
            }
            P_INDEX => {
                let p_index = node.parse(node_builder, value_builder, cache_builder);
                ValueKind::PIndex(p_index)
            }
            _ => unreachable!(), // Execution reaches this block
        }
    }
}
```

**Comment by Y-Nak** [comment]
Thanks for opening the issue and sorry for the late response.
> It seems like cameleon do not handles "pInvalidator" when it is inside Integer

Good catch! We need to add it to all non-register type nodes.
I'll fix it this weekend. I'll let you know when I finish the implementation.

**Comment by bschwind** [comment]
@Y-Nak I've also run into this issue with an Omron industrial camera (also a `pInvalidator` node). I added a simple diff which mostly ignores these (treats them as non-readable and non-writeable nodes, returns errors if you try to get or set values) to get past it.

What would a more holistic fix to this issue look like? I'm not sure if you have any work in progress on it, but if you have any tips on how it should be implemented I could try to start it.

**Comment by Y-Nak** [comment]
Sorry for the long delay, I was very busy in the past two months.
The fix is not so complicated, I guess. Anyway, I'll definitely take the time to fix it this weekend.

**Comment by bschwind** [comment]
@Y-Nak thanks! Let me know if I can help in any way, even if it's just testing on a camera that exhibits this behavior.

**Comment by H2WO4** [comment]
@Y-Nak Sorry for the late reply, and thanks for the fix!
But unfortunately, it seems that part of the config is still not handled by cameleon.

I've managed to identify precisely the problematic part:
The problem stems from the presence of multi-parameter functions, here `ROUND(x,y)`
The full line being parsed is `((ROUND(((0.1*(2**7))-0.5),0))/(2**7))`, and the codes panic when trying to parse the `,`

<details>
<summary>Full trace</summary>
thread 'main' panicked at 'unexpected character `,` in formula', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:744:18
stack backtrace:
   0:     0x555a918bdd3a - std::backtrace_rs::backtrace::libunwind::trace::h458cf307173bbb7e
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x555a918bdd3a - std::backtrace_rs::backtrace::trace_unsynchronized::h3a86a735716b3162
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555a918bdd3a - std::sys_common::backtrace::_print_fmt::h3c545795cfeff27f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x555a918bdd3a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfc7d1e1184be2a4d
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x555a918e14ce - core::fmt::write::hc6ef11db54e29a99
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/core/src/fmt/mod.rs:1208:17
   5:     0x555a918b81c5 - std::io::Write::write_fmt::h5a19bdd460e661f7
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/io/mod.rs:1682:15
   6:     0x555a918bdb05 - std::sys_common::backtrace::_print::he565e8fb2a73c8ba
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x555a918bdb05 - std::sys_common::backtrace::print::h3cdc14025f4ba73c
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x555a918bf2ef - std::panicking::default_hook::{{closure}}::hc8d15b4a44e5c68f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:267:22
   9:     0x555a918bf02b - std::panicking::default_hook::hd5c34ad5ebbaa14f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:286:9
  10:     0x555a918bf9fc - std::panicking::rust_panic_with_hook::h6b2d6d1ef385b7c1
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:688:13
  11:     0x555a918bf799 - std::panicking::begin_panic_handler::{{closure}}::h906b0280d4771185
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:579:13
  12:     0x555a918be1ec - std::sys_common::backtrace::__rust_end_short_backtrace::h75395d1a7d6a5847
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x555a918bf4a2 - rust_begin_unwind
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:575:5
  14:     0x555a910a5ba3 - core::panicking::panic_fmt::h6c49d3b35c325f7f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/core/src/panicking.rs:65:14
  15:     0x555a916e3ab9 - cameleon_genapi::formula::Lexer::peek::h92ed590b2b5bdf53
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:744:18
  16:     0x555a916e300f - cameleon_genapi::formula::Parser::eat::h3818ac4821d41341
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:536:15
  17:     0x555a916e2d8e - cameleon_genapi::formula::Parser::pow::hb6157ee4de5964cc
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:480:12
  18:     0x555a916e2d8e - cameleon_genapi::formula::Parser::unop::he9c4644b35ab06e8
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:474:13
  19:     0x555a916e24f9 - cameleon_genapi::formula::Parser::factor::haf725bf1ddd0505c
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:450:9
  20:     0x555a916e22e9 - cameleon_genapi::formula::Parser::term::h711dc8c9a1f30a03
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:442:9
  21:     0x555a916e20d9 - cameleon_genapi::formula::Parser::bit_shift::h04188dd57f533ae7
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:434:9
  22:     0x555a916e197c - cameleon_genapi::formula::Parser::rel::h8bfdbe22d752e7eb
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:424:9
  23:     0x555a916e1769 - cameleon_genapi::formula::Parser::eq::h5e1412a13e936997
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:416:9
  24:     0x555a916e15d9 - cameleon_genapi::formula::Parser::bitwise_and::h2a972549a53c5c49
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:412:9
  25:     0x555a916e1449 - cameleon_genapi::formula::Parser::bitwise_xor::h6eaed3cbff04f901
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:408:9
  26:     0x555a916e12b9 - cameleon_genapi::formula::Parser::bitwise_or::h3d2225fe69c852ff
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:404:9
  27:     0x555a916e1129 - cameleon_genapi::formula::Parser::logical_and::hc0ec9a390006eba3
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:400:9
  28:     0x555a916e0d43 - cameleon_genapi::formula::Parser::logical_or::h6bf7d14142fd12fd
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:396:9
  29:     0x555a916e0d43 - cameleon_genapi::formula::Parser::expr::h2b24ea898f5eaec5
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:380:20
  30:     0x555a916e2d02 - cameleon_genapi::formula::Parser::primary::he104e741849443b9
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:523:28
  31:     0x555a916e2d02 - cameleon_genapi::formula::Parser::pow::hb6157ee4de5964cc
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:479:20
  32:     0x555a916e2d02 - cameleon_genapi::formula::Parser::unop::he9c4644b35ab06e8
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:474:13
  33:     0x555a916e24f9 - cameleon_genapi::formula::Parser::factor::haf725bf1ddd0505c
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:450:9
  34:     0x555a916e22e9 - cameleon_genapi::formula::Parser::term::h711dc8c9a1f30a03
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:442:9
  35:     0x555a916e20d9 - cameleon_genapi::formula::Parser::bit_shift::h04188dd57f533ae7
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:434:9
  36:     0x555a916e197c - cameleon_genapi::formula::Parser::rel::h8bfdbe22d752e7eb
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:424:9
  37:     0x555a916e1769 - cameleon_genapi::formula::Parser::eq::h5e1412a13e936997
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:416:9
  38:     0x555a916e15d9 - cameleon_genapi::formula::Parser::bitwise_and::h2a972549a53c5c49
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:412:9
  39:     0x555a916e1449 - cameleon_genapi::formula::Parser::bitwise_xor::h6eaed3cbff04f901
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:408:9
  40:     0x555a916e12b9 - cameleon_genapi::formula::Parser::bitwise_or::h3d2225fe69c852ff
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:404:9
  41:     0x555a916e1129 - cameleon_genapi::formula::Parser::logical_and::hc0ec9a390006eba3
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:400:9
  42:     0x555a916e0d43 - cameleon_genapi::formula::Parser::logical_or::h6bf7d14142fd12fd
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:396:9
  43:     0x555a916e0d43 - cameleon_genapi::formula::Parser::expr::h2b24ea898f5eaec5
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:380:20
  44:     0x555a916e2a00 - cameleon_genapi::formula::Parser::primary::he104e741849443b9
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:494:24
  45:     0x555a916e2a00 - cameleon_genapi::formula::Parser::pow::hb6157ee4de5964cc
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:479:20
  46:     0x555a916e2a00 - cameleon_genapi::formula::Parser::unop::he9c4644b35ab06e8
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:474:13
  47:     0x555a916e24f9 - cameleon_genapi::formula::Parser::factor::haf725bf1ddd0505c
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:450:9
  48:     0x555a916e22e9 - cameleon_genapi::formula::Parser::term::h711dc8c9a1f30a03
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:442:9
  49:     0x555a916e20d9 - cameleon_genapi::formula::Parser::bit_shift::h04188dd57f533ae7
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:434:9
  50:     0x555a916e197c - cameleon_genapi::formula::Parser::rel::h8bfdbe22d752e7eb
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:424:9
  51:     0x555a916e1769 - cameleon_genapi::formula::Parser::eq::h5e1412a13e936997
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:416:9
  52:     0x555a916e15d9 - cameleon_genapi::formula::Parser::bitwise_and::h2a972549a53c5c49
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:412:9
  53:     0x555a916e1449 - cameleon_genapi::formula::Parser::bitwise_xor::h6eaed3cbff04f901
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:408:9
  54:     0x555a916e12b9 - cameleon_genapi::formula::Parser::bitwise_or::h3d2225fe69c852ff
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:404:9
  55:     0x555a916e1129 - cameleon_genapi::formula::Parser::logical_and::hc0ec9a390006eba3
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:400:9
  56:     0x555a916e0d43 - cameleon_genapi::formula::Parser::logical_or::h6bf7d14142fd12fd
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:396:9
  57:     0x555a916e0d43 - cameleon_genapi::formula::Parser::expr::h2b24ea898f5eaec5
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:380:20
  58:     0x555a916e2a00 - cameleon_genapi::formula::Parser::primary::he104e741849443b9
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:494:24
  59:     0x555a916e2a00 - cameleon_genapi::formula::Parser::pow::hb6157ee4de5964cc
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:479:20
  60:     0x555a916e2a00 - cameleon_genapi::formula::Parser::unop::he9c4644b35ab06e8
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:474:13
  61:     0x555a916e24f9 - cameleon_genapi::formula::Parser::factor::haf725bf1ddd0505c
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:450:9
  62:     0x555a916e22e9 - cameleon_genapi::formula::Parser::term::h711dc8c9a1f30a03
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:442:9
  63:     0x555a916e20d9 - cameleon_genapi::formula::Parser::bit_shift::h04188dd57f533ae7
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:434:9
  64:     0x555a916e197c - cameleon_genapi::formula::Parser::rel::h8bfdbe22d752e7eb
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:424:9
  65:     0x555a916e1769 - cameleon_genapi::formula::Parser::eq::h5e1412a13e936997
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:416:9
  66:     0x555a916e15d9 - cameleon_genapi::formula::Parser::bitwise_and::h2a972549a53c5c49
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:412:9
  67:     0x555a916e1449 - cameleon_genapi::formula::Parser::bitwise_xor::h6eaed3cbff04f901
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:408:9
  68:     0x555a916e12b9 - cameleon_genapi::formula::Parser::bitwise_or::h3d2225fe69c852ff
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:404:9
  69:     0x555a916e1129 - cameleon_genapi::formula::Parser::logical_and::hc0ec9a390006eba3
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:400:9
  70:     0x555a916e0d43 - cameleon_genapi::formula::Parser::logical_or::h6bf7d14142fd12fd
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:396:9
  71:     0x555a916e0d43 - cameleon_genapi::formula::Parser::expr::h2b24ea898f5eaec5
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:380:20
  72:     0x555a916e4134 - cameleon_genapi::formula::parse::h2ac5bb7fe228c716
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/formula.rs:348:5
  73:     0x555a9147b240 - cameleon_genapi::parser::formula::<impl cameleon_genapi::parser::Parse for cameleon_genapi::formula::Expr>::parse::h2d010d6939a16774
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/formula.rs:32:9
  74:     0x555a911b8dd4 - cameleon_genapi::parser::xml::Node::parse::h628317a5b2f9551e
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/xml.rs:45:9
  75:     0x555a9147b2ac - cameleon_genapi::parser::formula::<impl cameleon_genapi::parser::Parse for cameleon_genapi::formula::Formula>::parse::h08ed9f474496a2f6
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/formula.rs:19:20
  76:     0x555a911b9254 - cameleon_genapi::parser::xml::Node::parse::hd12126b8f305d5e2
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/xml.rs:45:9
  77:     0x555a910e17c1 - cameleon_genapi::parser::swiss_knife::<impl cameleon_genapi::parser::Parse for cameleon_genapi::swiss_knife::SwissKnifeNode>::parse::h65ca96cfbab85864
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/swiss_knife.rs:40:23
  78:     0x555a911b8f84 - cameleon_genapi::parser::xml::Node::parse::h9a58af7390c3b127
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/xml.rs:45:9
  79:     0x555a91293fd4 - <alloc::vec::Vec<cameleon_genapi::store::NodeData> as cameleon_genapi::parser::Parse>::parse::hd22b10c60cc4d0e1
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/mod.rs:174:63
  80:     0x555a911b8f54 - cameleon_genapi::parser::xml::Node::parse::h8ec7fbfab606b526
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/xml.rs:45:9
  81:     0x555a912ccaba - <cameleon_genapi::parser::group::GroupNode as cameleon_genapi::parser::Parse>::parse::hdb36a5bc5872cf92
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/group.rs:29:43
  82:     0x555a911b8d74 - cameleon_genapi::parser::xml::Node::parse::h5d3860ff1fb54349
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/xml.rs:45:9
  83:     0x555a9129456b - <alloc::vec::Vec<cameleon_genapi::store::NodeData> as cameleon_genapi::parser::Parse>::parse::hd22b10c60cc4d0e1
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/mod.rs:197:39
  84:     0x555a911b8f54 - cameleon_genapi::parser::xml::Node::parse::h8ec7fbfab606b526
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/xml.rs:45:9
  85:     0x555a91464e17 - cameleon_genapi::parser::parse::h62ac4cdf112f9c81
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/parser/mod.rs:71:39
  86:     0x555a9133cc41 - cameleon_genapi::builder::GenApiBuilder<T,U,S>::build::h90c7f23b8df8c6ca
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-genapi-0.1.8/src/builder.rs:30:24
  87:     0x555a91498d94 - <cameleon::genapi::DefaultGenApiCtxt as cameleon::genapi::FromXml>::from_xml::hd0b3e37fcf8bd674
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-0.1.8/src/genapi/mod.rs:247:50
  88:     0x555a913ceaf0 - cameleon::camera::Camera<Ctrl,Strm,Ctxt>::load_context::h9dc339f62ce0aa9a
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cameleon-0.1.8/src/camera.rs:248:26
</details>
