### ISSUE TITLE
Spurious `DataDiscarded` errors when streaming from cameras

### ISSUE THREAD

**Issue by strohel** [cameleon-rs/cameleon#156]
Filing this to track an issue discovered in https://github.com/cameleon-rs/cameleon/pull/153#issuecomment-1465470049 - that `PayloadReceiver::*recv*()` methods sometimes spuriously return `InvalidPayload("trailer status indicates error: DataDiscarded")` error.

The error is recoverable and not really frequent, so this is definitely not critical.

To reproduce:
1. Run the `stream` example with current `main`

We now see this has been "always" happening for us at a slow rate (with occassional clusters of higher frequency) with the 0.1.8 release (mind logarithmic axis, truncated error string):
![image](https://user-images.githubusercontent.com/145366/224990688-61209d50-ca76-48cc-bef1-36d3fbd513d2.png)

Tonari's internal tracking issue https://github.com/tonarino/portal/issues/2344.

### Meta
- Which manufacturer's camera did you use? What is the model name of the camera?
  - iDS U3-388xLE-C, Omron STC-BCS642U3V-BL (@bschwind please correct me if I'm wrong)
- Which `Cameleon` version are you using?
  - 0.1.8, https://github.com/tonarino/cameleon/tree/recv-blocking @ 186525d, https://github.com/Y-Nak/cameleon/tree/test-stream @ 72489df3ca0cc9f324bf2446dc19c346cf332630

**Comment by Y-Nak** [comment]
Could you re-run the same script with the current `main` if it's not so much trouble? I'm really interested in the outcome.

**Comment by strohel** [comment]
@Y-Nak with 1023142 (current main) I still sometimes get:
```
     Running `target/debug/examples/stream`
payload receive error: invalid payload has been sent: trailer status indicates error: DataDiscarded
payload receive error: invalid payload has been sent: trailer status indicates error: DataDiscarded
payload receive error: invalid payload has been sent: trailer status indicates error: DataDiscarded
payload received! block_id: 3, timestamp: 285321.20223315s
ImageInfo { width: 3088, height: 2076, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6410688 }

payload received! block_id: 4, timestamp: 285321.2222338s
ImageInfo { width: 3088, height: 2076, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6410688 }

payload received! block_id: 5, timestamp: 285321.2422345s
ImageInfo { width: 3088, height: 2076, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6410688 }

payload received! block_id: 6, timestamp: 285321.26223515s
ImageInfo { width: 3088, height: 2076, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6410688 }

payload received! block_id: 7, timestamp: 285321.28223585s
ImageInfo { width: 3088, height: 2076, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6410688 }

payload received! block_id: 8, timestamp: 285321.3022365s
ImageInfo { width: 3088, height: 2076, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6410688 }

payload received! block_id: 9, timestamp: 285321.3222372s
ImageInfo { width: 3088, height: 2076, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6410688 }
```

A lot of times I correctly get the 10 frames, once I get the 10 DataDiscarded errors, sometimes first 2-4 frames error.

This is with `/sys/module/usbcore/parameters/usbfs_memory_mb` set to 1000 (1 GB).
