### ISSUE TITLE
Health of this project - why require libusb

### ISSUE THREAD

**Issue by wlwatkins** [cameleon-rs/cameleon#185]
Hi, 

I had a test with this libary, and I am impressed on how fast I can program a camera using genicam in rust compared to wrapping the manufactures dll. 

However I wanted to know about the health of this project, if it is still maintained and weither the annouce roadmap is still being worked on. 

Second question was why one needs to install winusb (libusb). and wouldn't the cti files be enough for genicam to talk to them? the issue i have with this approach is that the manufactures software does not recognise the camera after i have updated the driver to winusb. 

thanks

**Comment by bschwind** [comment]
> However I wanted to know about the health of this project, if it is still maintained and weither the annouce roadmap is still being worked on.

Answering honestly, this project is currently in a state of "PRs / bugfixes will still be tested/merged, but there is no active development for new features"

> Second question was why one needs to install winusb (libusb). and wouldn't the cti files be enough for genicam to talk to them?

I don't know the details on why this architecture was chosen, sorry. I've also never worked with .cti files in relation to genicam, but you still need to either:

* Talk to the USB device directly from user code (as this library does, with libusb)
* Talk to a driver which talks to the USB device

The second path is not well supported by cameleon, from what I know. You can try disabling the `libusb` feature from the [cameleon-device](https://crates.io/crates/cameleon-device/0.1.12) crate and adding in your own code to read a .cti file and do whatever it is you do with them, but I have no concrete experience with that path.

**Comment by wlwatkins** [comment]
Thanks for the response. I'll close the issue as you have answered the question. It can be reopened if anything changes
