### ISSUE TITLE
Error when running the "stream" example with a FLIR Blackfly S BFS-U3-63S4C

### ISSUE THREAD

**Issue by zanshi** [cameleon-rs/cameleon#94]
Hi! Really exciting project, I'd love to help solve this issue.

- What did you expect to happen? What did actually happen?
  - I expected the `stream` example to receive 10 frames and then quit.
  - The example panicked with the following error: 
     `thread 'main' panicked at 'called Result::unwrap() on an Err value: ControlError(Io(invalid status: GenCp(InvalidAddress)))', cameleon/examples/stream.rs:19:27`
- How to reproduce the issue?
  - Run the `stream` example with the FLIR Blackfly S BFS-U3-63S4C camera.
  - I tried debugging the issue a bit and found that the camera returns "InvalidAddress" after sending to address `1610678271` in `send_cmd`

Contents of `cmd` that was send to the camera:
```
cmd:
  ccd:
    flag: cameleon_device::u3v::protocol::cmd::CommandFlag::RequestAck
    scd_kind: cameleon_device::u3v::protocol::cmd::ScdKind::ReadMem
    scd_len: 12
    request_id: 77
  scd:
    address: 1610678271
    read_length: 1012
  cmd_len: 24
  ack_len: 1024
```

Output from `cargo run --features=libusb --example u3v_register_map`:
```
### Technology Agnostic Boot Register Map ###

gencp_version: 1.0.0
manufacturer_name: FLIR
model_name: Blackfly S BFS-U3-63S4C
family_name: Ok(Some("GEN3-USB"))
device_version: 1801.0.9.0
manufacturer_name: FLIR
serial_number:
manifest_table_address: 262144
sbrm_address: 65536
device_software_interface_version: Ok(None)
maximum_device_response_time: Ok(200ms)
is_user_defined_name_supported: true
user_defined_name: Some("")
is_multi_event_supported: false
is_multi_event_enabled: false
is_stacked_commands_supported: false

### Technology Specifig Boot Register Map ###

u3v_version: 1.0.0
maximum_command_transfer_length: 1024
maximum_acknowledge_transfer_length: 1024
number_of_stream_channel: 1
sirm_address: Some(131072)
sirm_length: Some(48)
eirm_address: Some(163840)
eirm_length: Some(12)
iidc2_address: None
current_speed: SuperSpeed

### Manifest Entry 0 ###

GenICam file version: 1.0.0
GenICam file address: 1610612736
GenICam file size: 68507
GenICam file compression type: Zip
GenICam file type: DeviceXml
GenICam file schema version: 1.1.0

### Streaming Interface Register Map ###

payload_size_alignment: 8
is_stream_enable: false
required_payload_size: 6291456
required_leader_size: 52
required_trailer_size: 36
maximum_leader_size: 0
maximum_trailer_size: 0
payload_transfer_size: 0
payload_transfer_count: 0
payload_final_transfer1_size: 0
payload_final_transfer2_size: 0
```

I'd be happy to provide additional information.

### Meta
- Which manufacturer's camera did you use?
  - FLIR
- What is the model name of the camera?
  - Blackfly S BFS-U3-63S4C
```
### Device Information ###
GenCP Version: 1.0.0
U3V Version: 1.0.0
Vendor Name: FLIR
Model Name: Blackfly S BFS-U3-63S4C
Family Name: GEN3-USB
Manufacturer Information: Jan  2 2018 09:36:22
```

- Which `Cameleon` version are you using?
  - Latest commit on the main branch as of 2021-06-08, https://github.com/cameleon-rs/cameleon/commit/9c8f0f63f829d05f917cde599164e3e0b08398e3

**Comment by Y-Nak** [comment]
Thank you @zanshi for opening an issue and great details report.

Seeing your report, the address seems to fit into the valid range specified in `Manifest Entry`,  but it's not 2-bytes aligned. So I guess that the FLIR camera would need to read from an address that is at least 2-bytes aligned.
I opened #95 to test my assumption is correct. 
Could you run the `stream` example on the branch, please?

**Comment by zanshi** [comment]
Hi again.

One step closer! On that branch I got this error: `thread 'main' panicked at 'called Result::unwrap() on an Err value: ControlError(Io(invalid status: UsbSpecific(PayloadSizeNotAligned)))', cameleon/examples/stream.rs:22:49`

**Comment by zanshi** [comment]
Update:

```
payload received! block_id: 0, timestamp: 1594.791139704s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 1, timestamp: 1594.807906736s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 2, timestamp: 1594.824674888s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 3, timestamp: 1594.841442736s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 4, timestamp: 1594.858210088s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 5, timestamp: 1594.874978088s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 6, timestamp: 1594.89174548s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 7, timestamp: 1594.90851324s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 8, timestamp: 1594.925280536s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }

payload received! block_id: 9, timestamp: 1594.942048112s
ImageInfo { width: 3072, height: 2048, x_offset: 0, y_offset: 0, pixel_format: BayerRG8, image_size: 6291456 }
```

:tada: 

I tried just changing `52` to `56` in a debugger and that worked! So maybe round up to nearest byte aligned value?

**Comment by Y-Nak** [comment]
Cool! Thanks for your investigation. I didn't realize a leader should also be aligned.
I fixed it by aligning the leader and trailer size. Could you run the example on the branch again?

**Comment by zanshi** [comment]
It works now! Awesome response :)

**Comment by Y-Nak** [comment]
Thanks for your contribution:+1:
